# Generated by Django 5.2.9 on 2026-01-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('leader', 'Leader'), ('admin', 'Admin'), ('data_entry', 'Data Entry')], db_index=True, default='learner', max_length=32),
        ),
    ]
