# Generated by Django 5.2.9 on 2026-02-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('leader', 'Leader'), ('admin', 'Admin'), ('data_entry', 'Data Entry'), ('school', 'School Admin')], db_index=True, default='learner', max_length=32),
        ),
    ]
