# Generated by Django 6.0.2 on 2026-03-31 14:06

from django.db import migrations
import uuid


def fix_empty_emails(apps, schema_editor):
    """Set empty emails to unique placeholder values."""
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(email=''):
        user.email = f"placeholder_{user.id}_{uuid.uuid4().hex[:8]}@placeholder.local"
        user.save(update_fields=['email'])


def reverse_empty_emails(apps, schema_editor):
    """Reverse migration - not needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_teacher_schools'),
    ]

    operations = [
        migrations.RunPython(fix_empty_emails, reverse_empty_emails),
    ]
