# Generated by Codex on 2026-05-05

from __future__ import annotations

from django.db import migrations, models


def forwards(apps, schema_editor):
    user_model = apps.get_model("users", "User")
    legacy_role = "lead" + "er"
    user_model.objects.filter(role=legacy_role).update(role="program_manager")


def backwards(apps, schema_editor):
    user_model = apps.get_model("users", "User")
    legacy_role = "lead" + "er"
    user_model.objects.filter(role="program_manager").update(role=legacy_role)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_unique_email"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("learner", "Learner"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("program_manager", "Program Manager"),
                    ("admin", "Admin"),
                    ("data_entry", "Data Entry"),
                    ("school", "School Admin"),
                    ("curriculum_designer", "Curriculum Designer"),
                ],
                db_index=True,
                default="learner",
                max_length=32,
            ),
        ),
    ]
