# Generated by Codex on 2026-05-06

from __future__ import annotations

from django.db import migrations, models


def forwards(apps, schema_editor):
    user_model = apps.get_model("users", "User")
    user_model.objects.filter(role="data_entry").update(role="curriculum_designer")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_program_manager_role"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("learner", "Learner"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("program_manager", "Program Manager"),
                    ("admin", "Admin"),
                    ("school", "School Admin"),
                    ("curriculum_designer", "Curriculum Designer"),
                ],
                db_index=True,
                default="learner",
                max_length=32,
            ),
        ),
    ]
