# Generated by Django 5.2.9 on 2026-01-13 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_change_learner_to_parent_child_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='learner',
            new_name='core_learne_parent__969178_idx',
            old_name='core_learne_parent__idx',
        ),
        migrations.AlterField(
            model_name='learner',
            name='parent',
            field=models.ForeignKey(help_text='Parent/guardian who manages this learner', limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learner',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='School/organization (optional until parent is assigned)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
