# Generated by Django 5.2.9 on 2026-01-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_user_to_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='current_class',
            field=models.CharField(blank=True, default='', help_text='Current class/grade', max_length=100),
        ),
        migrations.AddField(
            model_name='learner',
            name='current_school',
            field=models.CharField(blank=True, default='', help_text='Current school name', max_length=255),
        ),
    ]
