# Generated by Django 5.2.9 on 2026-01-13 01:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_school_and_class_to_learner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], db_index=True, default='present', max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.learner')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'core_attendance',
                'ordering': ['-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Session date')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('attendance_marked', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, help_text='Session notes or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learners', models.ManyToManyField(help_text='Learners in this session', related_name='sessions_attended', through='core.Attendance', to='core.learner')),
                ('module', models.ForeignKey(help_text='Module/curriculum being taught', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.module')),
                ('teacher', models.ForeignKey(help_text='Teacher delivering this session', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_taught', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'core_session',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.session'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['teacher', 'date'], name='core_sessio_teacher_eb9d88_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', 'date'], name='core_sessio_status_5a068d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'learner')},
        ),
    ]
