# Generated by Django 5.2.9 on 2026-01-13 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_session_and_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who captured this artifact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
