# Generated by Django 5.2.9 on 2026-01-13 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_created_by_to_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(choices=[('robotics', 'Robotics'), ('coding', 'Coding'), ('3d_printing', '3D Printing'), ('electronics', 'Electronics'), ('ai_ml', 'AI & Machine Learning'), ('design', 'Design & Fabrication')], db_index=True, max_length=50)),
                ('min_age', models.PositiveIntegerField(default=6, help_text='Minimum age for this course')),
                ('max_age', models.PositiveIntegerField(default=18, help_text='Maximum age for this course')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='If set, course is only for this school. If null, available globally.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'core_course',
                'ordering': ['domain', 'min_age', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_number', models.PositiveIntegerField(default=1, help_text='Order of this level (1, 2, 3...)')),
                ('name', models.CharField(help_text="e.g., 'Level 1: Foundations'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('learning_outcomes', models.JSONField(default=list, help_text='List of learning outcomes for this level')),
                ('required_modules_count', models.PositiveIntegerField(default=4, help_text='Number of modules to complete')),
                ('required_artifacts_count', models.PositiveIntegerField(default=6, help_text='Minimum artifacts to submit')),
                ('required_assessment_score', models.PositiveIntegerField(default=70, help_text='Minimum assessment score (0-100)')),
                ('requires_teacher_confirmation', models.BooleanField(default=False, help_text='If true, teacher must confirm completion')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='core.course')),
                ('required_modules', models.ManyToManyField(blank=True, help_text='Specific modules required for this level', related_name='course_levels', to='core.module')),
            ],
            options={
                'verbose_name': 'Course Level',
                'verbose_name_plural': 'Course Levels',
                'db_table': 'core_course_level',
                'ordering': ['course', 'level_number'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('achievement_type', models.CharField(choices=[('level_complete', 'Level Completed'), ('course_complete', 'Course Completed'), ('skill_mastery', 'Skill Mastery'), ('participation', 'Participation'), ('special', 'Special Achievement')], default='level_complete', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=100)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.learner')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.courselevel')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'db_table': 'core_achievement',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerCourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When all levels completed', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course')),
                ('current_level', models.ForeignKey(blank=True, help_text='Current level the learner is on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_learners', to='core.courselevel')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='core.learner')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'db_table': 'core_learner_course_enrollment',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerLevelProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modules_completed', models.PositiveIntegerField(default=0)),
                ('artifacts_submitted', models.PositiveIntegerField(default=0)),
                ('assessment_score', models.PositiveIntegerField(default=0, help_text='Best assessment score')),
                ('teacher_confirmed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to='core.learnercourseenrollment')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_progress', to='core.courselevel')),
            ],
            options={
                'verbose_name': 'Level Progress',
                'verbose_name_plural': 'Level Progress Records',
                'db_table': 'core_learner_level_progress',
                'ordering': ['level__level_number'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['domain', 'is_active'], name='core_course_domain_ac180e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['min_age', 'max_age'], name='core_course_min_age_0ba5c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courselevel',
            unique_together={('course', 'level_number')},
        ),
        migrations.AlterUniqueTogether(
            name='learnercourseenrollment',
            unique_together={('learner', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='learnerlevelprogress',
            unique_together={('enrollment', 'level')},
        ),
    ]
