# Generated by Django 5.2.9 on 2026-01-23 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_courses_and_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='competences',
            field=models.TextField(blank=True, help_text='Skills/Competences gained'),
        ),
        migrations.AddField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text content, videos, images'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Primary pathway this module belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='core.course'),
        ),
        migrations.AddField(
            model_name='module',
            name='materials',
            field=models.TextField(blank=True, help_text='Required materials'),
        ),
        migrations.AddField(
            model_name='module',
            name='suggested_activities',
            field=models.TextField(blank=True, help_text='Suggested learning experiences'),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='core.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
