# Generated by Django 5.2.9 on 2026-01-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_module_competences_module_content_module_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['domain', 'name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_min_age_0ba5c9_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='course',
            name='min_age',
        ),
    ]
