# Generated by Django 5.2.9 on 2026-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_domain_ac180e_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='domain',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='core_course_is_acti_bcef00_idx'),
        ),
    ]
