# Generated by Django 5.2.9 on 2026-01-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='media_files',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded media files [{type, url, name}]'),
        ),
    ]
