# Generated by Django 5.2.9 on 2026-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_career_tenant_alter_module_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='competences',
            field=models.JSONField(blank=True, default=list, help_text='List of competencies'),
        ),
        migrations.AlterField(
            model_name='module',
            name='materials',
            field=models.JSONField(blank=True, default=list, help_text='List of materials'),
        ),
        migrations.AlterField(
            model_name='module',
            name='suggested_activities',
            field=models.JSONField(blank=True, default=list, help_text='List of activities'),
        ),
    ]
