# Generated by Django 5.2.9 on 2026-01-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_module_competences_alter_module_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tenant',
        ),
    ]
