# Generated by Django 5.2.9 on 2026-01-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_activity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='badge_name',
            field=models.CharField(blank=True, help_text='Name of the badge earned upon completion', max_length=255),
        ),
    ]
