# Generated by Django 5.2.9 on 2026-01-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_badge_name_to_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='badge_name',
        ),
        migrations.AddField(
            model_name='module',
            name='badge_name',
            field=models.CharField(blank=True, help_text='Name of the badge earned upon completion of this module', max_length=255),
        ),
    ]
