# Generated by Django 5.2.9 on 2026-02-10 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_move_badge_name_course_to_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Teachers assigned to this course', limit_choices_to={'role': 'teacher'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
