# Generated by Django 5.2.9 on 2026-02-10 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_learner_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list, help_text='List of questions with options and correct answers')),
                ('passing_score', models.IntegerField(default=70, help_text='Minimum score to pass (0-100)')),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Time limit in minutes (optional)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Teacher who created this quiz', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, help_text='Module this quiz is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='core.module')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'core_quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_name', models.CharField(help_text="Name of the badge (e.g., 'Robotics Master', 'Code Ninja')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this badge represents')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('awarded_by', models.ForeignKey(blank=True, help_text='Teacher who awarded this badge', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(help_text='Learner who earned this badge', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.learner')),
                ('module', models.ForeignKey(blank=True, help_text='Module associated with this badge (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to='core.module')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'core_badge',
                'ordering': ['-awarded_at'],
                'indexes': [models.Index(fields=['learner', 'awarded_at'], name='core_badge_learner_beb967_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=list, help_text='List of answer indices')),
                ('score', models.IntegerField(help_text='Score achieved (0-100)')),
                ('passed', models.BooleanField(default=False, help_text='Whether the student passed')),
                ('feedback', models.TextField(blank=True, help_text="Teacher's feedback on this attempt")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts_graded', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='core.learner')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.quiz')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'db_table': 'core_quiz_attempt',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['learner', 'quiz'], name='core_quiz_a_learner_17d5bd_idx'), models.Index(fields=['quiz', 'completed_at'], name='core_quiz_a_quiz_id_49197a_idx')],
            },
        ),
    ]
