# Generated by Django 5.2.9 on 2026-03-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_teachertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='module',
            field=models.ForeignKey(blank=True, help_text='The specific microcredential/module this artifact is tied to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.module'),
        ),
    ]
