# Generated by Django 5.2.11 on 2026-03-29 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_artifact_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Optional reason provided when rejecting a student artifact'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the teacher reviewed this artifact', null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who approved or rejected this student submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artifact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', help_text='Approval status; teacher-captured artifacts default to approved', max_length=16),
        ),
        migrations.AddField(
            model_name='artifact',
            name='uploaded_by_student',
            field=models.BooleanField(db_index=True, default=False, help_text='True when submitted by the student directly'),
        ),
    ]
