# Generated by Django 6.0.2 on 2026-04-14 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_artifact_approval_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='School/organization (optional for independent learners)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
