# Generated by Codex on 2026-05-05

from __future__ import annotations

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_module_peer_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="module",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
            ),
        ),
    ]
