# Generated by Django 6.0.2 on 2026-05-05 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_module_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='module',
            name='module_review_status_idx',
        ),
        migrations.RenameIndex(
            model_name='adminoverride',
            new_name='core_admin__learner_5c590f_idx',
            old_name='admin_override_learner_layer_ref_idx',
        ),
        migrations.AlterField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Related pathway', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.pathway'),
        ),
        migrations.AlterField(
            model_name='adminoverride',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='badgerecord',
            name='artifacts',
            field=models.ManyToManyField(blank=True, help_text='Evidence supporting this badge (at least one required at issuance — PRD F-09).', related_name='badge_records', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='badgerecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='badgerecord',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.badgetemplate'),
        ),
        migrations.AlterField(
            model_name='badgerecord',
            name='verification_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='criteria',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='icon_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='certificationrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='certificationtemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='growthprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learningtask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microcredentialrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microcredentialtemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(blank=True, help_text='[Deprecated] Use `program` instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='core.pathway'),
        ),
        migrations.AlterField(
            model_name='module',
            name='outcome_statement',
            field=models.CharField(blank=True, default='', help_text="One sentence: 'Learner can…' shown to learners", max_length=500),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='age_band_min',
            field=models.PositiveIntegerField(default=6, help_text='Minimum recommended age for this pathway'),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='age_band_target',
            field=models.PositiveIntegerField(default=12, help_text='Target/ideal starting age for this pathway'),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='color',
            field=models.CharField(blank=True, default='#3B82F6', help_text='Hex color code for UI theming (e.g. #3B82F6)', max_length=7),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Icon name, emoji, or URL for this pathway', max_length=100),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Teachers assigned to this pathway', limit_choices_to={'role': 'teacher'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='If set, pathway is only for this school. If null, available globally.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AlterField(
            model_name='podclass',
            name='schedule',
            field=models.JSONField(default=dict, help_text='e.g., {"days": ["Mon","Wed"], "time": "14:00"}'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, help_text="Learner-facing outcome statement, e.g. 'By the end you will be able to…'"),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.JSONField(default=list, help_text='List: [{"question": "...", "options": ["A","B","C"], "correct_answer": 0}]'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(default=list, help_text='List of answer indices, e.g. [0, 2, 1, 3]'),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weeklypulse',
            name='mood',
            field=models.IntegerField(db_index=True, default=0, help_text='0-100 scale'),
        ),
        migrations.AddIndex(
            model_name='pathway',
            index=models.Index(fields=['is_active'], name='core_pathwa_is_acti_4fe5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='pathway',
            index=models.Index(fields=['status'], name='core_pathwa_status_909940_idx'),
        ),
    ]
