# Generated by Django 6.0.2 on 2026-05-05 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_module_module_review_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('corrected', 'Corrected')], db_index=True, default='pending', max_length=16)),
                ('quality_rubric', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('offline_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('correction_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
                'db_table': 'core_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='badgerecord',
            name='unique_badge_per_learner',
        ),
        migrations.RemoveConstraint(
            model_name='certificationrecord',
            name='unique_certification_per_learner',
        ),
        migrations.RemoveConstraint(
            model_name='microcredentialrecord',
            name='unique_microcredential_per_learner',
        ),
        migrations.AddField(
            model_name='badgerecord',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.badgerecord'),
        ),
        migrations.AddField(
            model_name='badgerecord',
            name='correction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificationrecord',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.certificationrecord'),
        ),
        migrations.AddField(
            model_name='certificationrecord',
            name='correction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='microcredentialrecord',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.microcredentialrecord'),
        ),
        migrations.AddField(
            model_name='microcredentialrecord',
            name='correction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='artifact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_record', to='core.artifact'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='badge_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.badgetemplate'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='certification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.certificationtemplate'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='correction_of',
            field=models.ForeignKey(blank=True, help_text='Append-only correction lineage. Original evidence is never overwritten.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.evidence'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.learner'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='microcredential_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.microcredentialtemplate'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.module'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.learningtask'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='School/organization scope for this evidence.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.unit'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgerecord',
            name='evidence',
            field=models.ManyToManyField(blank=True, help_text='Canonical evidence supporting this badge.', related_name='badge_records', to='core.evidence'),
        ),
        migrations.AddField(
            model_name='certificationrecord',
            name='evidence',
            field=models.ManyToManyField(blank=True, help_text='Canonical evidence supporting this certification.', related_name='certification_records', to='core.evidence'),
        ),
        migrations.AddField(
            model_name='microcredentialrecord',
            name='evidence',
            field=models.ManyToManyField(blank=True, help_text='Canonical evidence supporting this microcredential.', related_name='microcredential_records', to='core.evidence'),
        ),
        migrations.AddConstraint(
            model_name='badgerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('correction_of__isnull', True)), fields=('template', 'learner'), name='unique_badge_per_learner'),
        ),
        migrations.AddConstraint(
            model_name='certificationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('correction_of__isnull', True)), fields=('template', 'learner'), name='unique_certification_per_learner'),
        ),
        migrations.AddConstraint(
            model_name='microcredentialrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('correction_of__isnull', True)), fields=('template', 'learner'), name='unique_microcredential_per_learner'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['learner', 'verification_status'], name='core_eviden_learner_839cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['module', 'verification_status'], name='core_eviden_module__6021ba_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['task', 'verification_status'], name='core_eviden_task_id_db98d4_idx'),
        ),
    ]
